plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.14'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'com.diffplug.spotless' version '7.2.1'
	id 'jacoco'
	id 'com.github.spotbugs' version '6.1.7'
}

group = 'com.signasource'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'com.bucket4j:bucket4j-core:8.10.1'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'org.springframework.boot:spring-boot-starter-mail'

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.17'

    // Firebase Cloud Messaging (push notifications)
    implementation 'com.google.firebase:firebase-admin:9.4.3'

    implementation 'com.google.api-client:google-api-client:2.9.0'

    // JJWT Dependencies
    implementation 'io.jsonwebtoken:jjwt-api:0.12.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.5'

	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	developmentOnly 'org.springframework.boot:spring-boot-docker-compose'

	runtimeOnly 'org.postgresql:postgresql'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'com.h2database:h2'
}

jacoco {
	toolVersion = "0.8.12"
}

tasks.named('test') {
	useJUnitPlatform()
	finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test

    reports {
        html.required = true
        xml.required = true
    }

    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: [
                '**/config/**',
                '**/dto/**',
                '**/entity/**',
                '**/exceptions/**',
                '**/config/**',
                '**/*Application*'
            ])
        }))
    }
}

jacocoTestCoverageVerification {
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: [
                '**/config/**',
                '**/dto/**',
                '**/entity/**',
                '**/exceptions/**',
                '**/config/**',
                '**/*Application*'
            ])
        }))
    }

    violationRules {
        rule {
            limit {
                minimum = 0.9
            }
        }
    }
}

check.dependsOn jacocoTestCoverageVerification

spotbugs {
	toolVersion = '4.8.6'
	ignoreFailures = false
	showProgress = false
	excludeFilter = file('config/spotbugs-exclude.xml')
}

spotbugsMain {
	reports {
		html.required = true
		xml.required = false
	}
}

spotbugsTest {
	reports {
		html.required = true
		xml.required = false
	}
}

spotless {
	java {
		target 'src/**/*.java'

		googleJavaFormat().aosp()

		removeUnusedImports()
		formatAnnotations()
		endWithNewline()

		custom('No wildcard imports') { String content ->
			if (content =~ /import\s+[\w.]+\*;/) {
				throw new AssertionError("Wildcard imports no están permitidos.")
			}
			content
		}
	}

	format 'misc', {
		target '*.md', '.gitignore', '.gitattributes'

		trimTrailingWhitespace()
		endWithNewline()
	}
}
