spring:
  application:
    name: signa-api

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8080

app:
  security:
    enabled: true

jwt:
  secret: change-this-secret-key-that-is-at-least-32-chars
  expiration: 86400000