spring:
  jpa:
    hibernate:
      ddl-auto: update

app:
  base-url: http://localhost:8080
  panel-url: http://localhost:5173
  cors:
    allowed-origins: http://localhost:5173

google-play:
  enabled: false
