spring:
  application:
    name: signa-api

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

app:
  base-url:

auth:
    google:
        client-id: ${GOOGLE_CLIENT_ID:default-client-id}
    jwt:
        secret: ${JWT_SECRET}
    token-expirations:
        password-reset: 3600000      # 1 hour
        access: 900000               # 15 minutes
        refresh: 604800000           # 7 days
        email-verification: 86400000 # 24 hours

firebase:
  enabled: true
  global-topic: global
  credentials-json: ${FIREBASE_CREDENTIALS_JSON:}
