-- Challenges seed — first steps and daily challenges, from Gamificación.xlsx (sheet "Challenges").
-- Copy is user-facing, so it is written in Spanish (rioplatense) unlike the rest of the codebase.
-- Upserts by `code`: editing a reward or a target here and restarting the API updates the catalog.
-- Ids are generated by the DB, never hardcoded (see store_items.sql).
-- FIRST_STEPS is the starter set; the DAILY ones only show up once every first step is claimed.
INSERT INTO challenges (id, code, title, description, challenge_type, criteria_type, criteria_value,
                        reward_type, reward_quantity, reward_duration_minutes, reward_multiplier_value,
                        active, display_order)
VALUES
    (gen_random_uuid(), 'first_steps_lesson', 'Completá tu primera lección',
     'Terminá una lección del curso.',
     'FIRST_STEPS', 'COMPLETE_LESSONS', 1, 'GEMS', 20, NULL, NULL, true, 1),
    (gen_random_uuid(), 'first_steps_camera', 'Probá la cámara en Práctica',
     'Resolvé un ejercicio con cámara.',
     'FIRST_STEPS', 'CAMERA_PRACTICES', 1, 'GEMS', 20, NULL, NULL, true, 2),
    (gen_random_uuid(), 'first_steps_friend', 'Sumá tu primer amigo en Social',
     'Mandá una solicitud de amistad.',
     'FIRST_STEPS', 'FRIEND_REQUESTS_SENT', 1, 'GEMS', 30, NULL, NULL, true, 3),
    (gen_random_uuid(), 'first_steps_streak', 'Volvé mañana y hacé racha de 2 días',
     'Practicá dos días seguidos.',
     'FIRST_STEPS', 'STREAK_DAYS', 2, 'GEMS', 30, NULL, NULL, true, 4),

    (gen_random_uuid(), 'daily_lessons', 'Estudiante constante',
     'Completá 3 lecciones en un día.',
     'DAILY', 'COMPLETE_LESSONS', 3, 'GEMS', 50, NULL, NULL, true, 1),
    (gen_random_uuid(), 'daily_camera', 'Practicá con cámara',
     'Completá 5 ejercicios con cámara en un día.',
     'DAILY', 'CAMERA_PRACTICES', 5, 'GEMS', 40, NULL, NULL, true, 2),
    (gen_random_uuid(), 'daily_perfect', 'Sesión perfecta',
     'Completá 3 lecciones sin errores en un día.',
     'DAILY', 'PERFECT_LESSONS', 3, 'XP_MULTIPLIER', 1, 30, 3.0, true, 3),
    (gen_random_uuid(), 'daily_xp', 'Experto del día',
     'Obtené 500 XP en un solo día.',
     'DAILY', 'EARN_XP', 500, 'GEMS', 60, NULL, NULL, true, 4)
ON CONFLICT (code) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    challenge_type = EXCLUDED.challenge_type,
    criteria_type = EXCLUDED.criteria_type,
    criteria_value = EXCLUDED.criteria_value,
    reward_type = EXCLUDED.reward_type,
    reward_quantity = EXCLUDED.reward_quantity,
    reward_duration_minutes = EXCLUDED.reward_duration_minutes,
    reward_multiplier_value = EXCLUDED.reward_multiplier_value,
    active = EXCLUDED.active,
    display_order = EXCLUDED.display_order;
