-- Store catalog seed — single source of truth for the shop.
-- Copy is user-facing, so it is written in Spanish (rioplatense) unlike the rest of the codebase.
-- Upserts by `code`: editing a price or a title here and restarting the API updates the catalog.
-- Ids are generated by the DB, never hardcoded: rows are identified by `code`. A literal id would
-- collide with the primary key of a row an earlier catalog already inserted under a different code,
-- and `ON CONFLICT (code)` does not catch a conflict on the primary key.
INSERT INTO shop_items (id, code, title, description, item_type, price_gems, quantity, duration_minutes, multiplier_value, active)
VALUES
    (gen_random_uuid(), 'life_refill_single', 'Una vida',
     'Recuperá una vida al instante y seguí con la lección donde la dejaste.',
     'LIFE', 20, 1, NULL, NULL, true),
    (gen_random_uuid(), 'life_refill_full', 'Vidas al máximo',
     'Recuperá tus 5 vidas de golpe y arrancá la próxima lección sin esperar.',
     'LIFE', 80, 5, NULL, NULL, true),
    (gen_random_uuid(), 'unlimited_lives_15m', 'Vidas infinitas',
     'Practicá 15 minutos sin perder vidas: equivocarte no te frena.',
     'UNLIMITED_LIVES', 60, 1, 15, NULL, true),
    (gen_random_uuid(), 'unlimited_lives_60m', 'Vidas infinitas extendidas',
     'Una hora entera de práctica sin límite de vidas, ideal para avanzar varias lecciones seguidas.',
     'UNLIMITED_LIVES', 180, 1, 60, NULL, true),
    (gen_random_uuid(), 'xp_multiplier_1_5x', 'Impulso de XP',
     'Ganá 1.5 veces más XP durante 30 minutos.',
     'XP_MULTIPLIER', 50, 1, 30, 1.5, true),
    (gen_random_uuid(), 'xp_multiplier_2x', 'Impulso de XP doble',
     'Ganá el doble de XP durante 30 minutos.',
     'XP_MULTIPLIER', 90, 1, 30, 2.0, true),
    (gen_random_uuid(), 'xp_multiplier_3x', 'Impulso de XP triple',
     'Ganá el triple de XP durante 30 minutos. El empujón más grande para escalar en el ranking semanal.',
     'XP_MULTIPLIER', 160, 1, 30, 3.0, true),
    (gen_random_uuid(), 'streak_shield_x1', 'Escudo de racha',
     'Protegé tu racha un día que no llegues a practicar.',
     'STREAK_SHIELD', 40, 1, NULL, NULL, true),
    (gen_random_uuid(), 'streak_shield_x3', 'Escudos de racha x3',
     'Tres días de protección para tu racha, guardados para cuando los necesites.',
     'STREAK_SHIELD', 100, 3, NULL, NULL, true),
    (gen_random_uuid(), 'streak_shield_x7', 'Escudos de racha x7',
     'Una semana entera de protección para tu racha, al mejor precio por día.',
     'STREAK_SHIELD', 210, 7, NULL, NULL, true),
    (gen_random_uuid(), 'mystery_chest', 'Cofre sorpresa',
     'Abrilo y llevate una recompensa al azar: gemas, una vida, un impulso de XP, vidas infinitas o un escudo de racha.',
     'MYSTERY_CHEST', 50, 1, NULL, NULL, true)
ON CONFLICT (code) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    item_type = EXCLUDED.item_type,
    price_gems = EXCLUDED.price_gems,
    quantity = EXCLUDED.quantity,
    duration_minutes = EXCLUDED.duration_minutes,
    multiplier_value = EXCLUDED.multiplier_value,
    active = EXCLUDED.active;

-- Retire items from previous catalogs. They are deactivated, not deleted: `purchases` has an FK to
-- `shop_items` and past purchases must keep resolving to the item they were made from.
UPDATE shop_items
SET active = false
WHERE code NOT IN (
    'life_refill_single', 'life_refill_full',
    'unlimited_lives_15m', 'unlimited_lives_60m',
    'xp_multiplier_1_5x', 'xp_multiplier_2x', 'xp_multiplier_3x',
    'streak_shield_x1', 'streak_shield_x3', 'streak_shield_x7',
    'mystery_chest'
);
